name: tinkercad
description: Simpe motivator trainer tracker app with tinder mechanics

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # architecture
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  riverpod: 2.3.6
  flutter_riverpod: 2.3.6
  hooks_riverpod: 2.3.6

  # tools
  flutter_hooks: ^0.18.5+1

  # widget
  cached_network_image: ^3.2.2
  assorted_layout_widgets: ^7.0.0
  sliver_tools: ^0.2.8
  visibility_detector: ^0.3.3
  modal_bottom_sheet: 3.0.0-pre
  gap: 3.0.0

  # stores
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # DI
  get_it: ^7.2.0

  # navigation
  go_router: ^7.1.1

  #firebase
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
